### ISSUE TITLE
Student cannot have more than one classes

### ISSUE THREAD

**Issue by munhuikim** [AY2425S1-CS2103T-T15-2/tp#222] opened 2024-10-30 15:44 UTC
![Uploading 스크린샷 2024-10-30 오후 11.43.39.png…]()

Expected: Input accepted
Actual: Error message

**Comment by sumomomomomo** [comment] 2024-10-31 16:18
Out of scope.

Duplicate of #224

**Closed by sumomomomomo** 2024-10-31 16:18 UTC
Labels: alpha-bug
